### ISSUE TITLE
Balance Druid Gearscore Dropped like a rock overnight

### ISSUE THREAD

**Issue by joelgriffiths** [anzz1/TacoTip#22] opened 2022-11-19 19:06 UTC
Not sure if this is the correct place to put this, but my fully enchanted, fully gemmed, 211 ilevel, near bis Balanced Druid, dropped from ~4200 to ~3850 overnight. Not sure if something changed that could affect this, but it doesn't seem right.

**Comment by anzz1** [comment] 2022-11-20 05:35
Sounds really strange indeed, as nothing related to the gearscore calculation has been changed in the addon for a while. In fact, last two updates were just added translations and the gearscore calculation has been the same since the original release in back in TBC.

Can you confirm that this happens with only TacoTip enabled? That you don't maybe have some other addon messing with the gearscore?

**Comment by anzz1** [comment] 2022-12-07 22:50
Closed as invalid for now, since the issue cannot be reproduced and more information is needed.

**Closed by anzz1** 2022-12-07 22:50 UTC
Labels: invalid

**Comment by joelgriffiths** [comment] 2022-12-08 15:09
Sorry. I will just leave a note.

After I filed this report, my GS started reporting correctly again, and I haven't seen the problem since.

**Comment by anzz1** [comment] 2022-12-08 16:11
Thanks for the follow-up. Will be reopening the ticket if issue resurfaces.
